name: invictus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.1.2
  # camera: ^0.11.0+2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  speech_to_text: ^7.0.0
  video_player: ^2.9.2
  sqflite: ^2.2.8+4
  flutter_cache_manager: ^3.3.1
  sqflite_common_ffi: ^2.3.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  sign_in_button: ^3.2.0
  flutter_web_auth: ^0.5.0
  geolocator: ^13.0.2
  # camera: ^0.11.0+2
  # camera: ^0.11.0+2
#   camera_android:

# dependency_overrides:
#   camera_android:
#     git:
#       url: https://github.com/elmar001/plugins.git
#       path: packages/camera/camera_android
#       ref: 5172b44088a4082ff0899594614c5380457d341b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

  assets:
    - assets/
    - assets/images/
    - assets/onboarding/
    - assets/splash.mp4
