// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:638937567376:web:a46f4e8db0759431a78815',
    messagingSenderId: '638937567376',
    projectId: 'invictus-8f34a',
    authDomain: 'invictus-8f34a.firebaseapp.com',
    storageBucket: 'invictus-8f34a.firebasestorage.app',
    measurementId: 'G-9K4GGEKJ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:638937567376:android:385cb57f13d3d442a78815',
    messagingSenderId: '638937567376',
    projectId: 'invictus-8f34a',
    storageBucket: 'invictus-8f34a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:638937567376:ios:79da3807cca6d5fda78815',
    messagingSenderId: '638937567376',
    projectId: 'invictus-8f34a',
    storageBucket: 'invictus-8f34a.firebasestorage.app',
    iosBundleId: 'com.example.invictus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:638937567376:ios:79da3807cca6d5fda78815',
    messagingSenderId: '638937567376',
    projectId: 'invictus-8f34a',
    storageBucket: 'invictus-8f34a.firebasestorage.app',
    iosBundleId: 'com.example.invictus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:638937567376:web:ba50e2b77f1c1a38a78815',
    messagingSenderId: '638937567376',
    projectId: 'invictus-8f34a',
    authDomain: 'invictus-8f34a.firebaseapp.com',
    storageBucket: 'invictus-8f34a.firebasestorage.app',
    measurementId: 'G-SCZFXR6J7C',
  );
}
